---
# control_flow.yml
- name: Example play showcasing control-flow
  hosts: localhost
  vars:
    homebrew_pkgs:
      - ssh-copy-id
      - gpg2
  tasks:
    - name: Print the packages to install if defined
      debug:
        msg: "Packages I want to install: {{ homebrew_pkgs }}"
      when: homebrew_pkgs|length > 0
    - name: Create the tmp dir
      file:
        path: "{{ ansible_env.HOME }}/tmp"
        state: directory
    - name: Touch some files
      file:
        path: "{{ ansible_env.HOME }}/tmp/{{ item }}"
        state: touch
      with_items:
        - foo
        - bar
    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_pkgs }}"


